services:
  auth_service:
    build:
      context: ./auth_service
    env_file:
      - ./auth_service/.env
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/app

  bot_service_api:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./bot_service:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8001

  bot_service_bot:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./bot_service:/app
    command: python -m app.bot.run

  celery_worker:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./bot_service:/app
    command: celery -A app.infra.celery_app.celery_app worker -l info

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
